### ISSUE TITLE
Should users be able to update a snippet instead of creating a new one

### ISSUE THREAD

**Issue by Daio-io** [code-wall/codebin#6]
At the moment if you query a snippet and then click share it will create a new one.

Something to consider if we want to allow users to update the snippet being viewed

**Comment by alechewitt** [comment]
Yes I think this is a good idea. Though requires some thought about who can do it...
I think only the user who initially creates the snippet can update it. Otherwise others could edit your snippet that you still need. This would suggest we would have to implement some kind of session everytime a user starts a new snippet.

**Comment by Daio-io** [comment]
Yeah, it would be good to avoid sessions and login stuff so maybe we should park this idea for now

**Comment by Daio-io** [comment]
Marked as invalid since it will not be implemented
